export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";
export const SET_COUNTER = "SET_COUNTER";
export const RANDOM_COUNTER = "RANDOM_COUNTER";
